# -*- coding: utf-8 -*-
"""03_LLM_API_CALL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JU4rGwxt2Vauf5j1AswinvWdCrfb7kFc

### Setting Environment Variables in Colab
"""

import os

# Set an environment variable
os.environ['GROQ_API_KEY'] = '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'
print("Environment variables set successfully.")

# Access an environment variable
api_key = os.getenv('GROQ_API_KEY')
print(f"Value of my api key: {api_key}")

"""### LLM API CALL using GROQ (Raw Method)"""

"""

Module 3 - Step 2: Call the LLM the RAW way - no SDK, just HTTP (BRUTE FORCE).

This shows what EVERY 'AI library' is secretly doing under the hood.

"""

import os
import json
import requests

# 1) Load the secret api key

# 2) The window's address (where we slide the note)
url = "https://api.groq.com/openai/v1/chat/completions"

# 3) The ENVELOPE: who we are + what we're sending
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json",
}

# 4) The LETTER: our actual order (the messages list + settings)

payload = {
    "model": "llama-3.3-70b-versatile",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user",   "content": "In one sentence, what is an API?"},
    ],
    "temperature": 0.7,
}

# 5) Slide the note through the window
response = requests.post(url, headers=headers, json=payload)

# 6) Look at the FULL raw reply the server sent back
print("=== FULL RAW RESPONSE ===")
print(json.dumps(response.json(), indent=2))

# 7) Dig out just the answer text
data = response.json()
print("\n=== JUST THE ANSWER ===")
print(data["choices"][0]["message"]["content"])

# 8) The server even tells us our token usage
print("\n=== TOKENS USED ===")
print(data["usage"])

"""### LLM API CALL using GROQ (Standard Method) - SDK"""

pip install groq

"""
Module 3 - Step 3: The SAME call, using the groq SDK (THE SHORTCUT).
It does the identical HTTP from Step 2 under the hood - just cleaner.
"""
import os
from groq import Groq

# 1) Load the api key

# 2) Create a 'client' - your personal assistant for talking to Groq
client = Groq(api_key=os.environ["GROQ_API_KEY"])

# 3) Make the call - one clean command instead of URL + headers + post
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user",   "content": "In one sentence, what is an API?"},
    ],
    temperature=0.7,
)

# 4) Dig out the answer - clean dot-access, no JSON peeling
print("=== ANSWER ===")
print(response.choices[0].message.content)

# 5) Token usage, also clean
print("\n=== TOKENS USED ===")
print(response.usage.total_tokens)

response = client.chat.completions.create(
    model = "llama-3.3-70b-versatile",
    messages = [
        {"role": "system", "content":"You are an experienced chef"},
        {"role": "user", "content": "tell me the recipe of tea in 1 line"}
    ],
    temperature = 0.7,
)
print(response.choices[0].message.content)

response = client.chat.completions.create(
    model = "llama-3.3-70b-versatile",
    messages = [
        {"role": "user", "content": "tell me my prev question"}
    ],
    temperature = 0.7,
)
print(response.choices[0].message.content)

"""### Giving the Bot a memory
##### REAL memory - keep appending to the messages list.
"""

import os
from groq import Groq

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# THIS list is the memory (the "notebook"). It grows every turn.
messages = [{"role": "system", "content": "You are a helpful assistant."}]

# ----- Turn 1 -----
messages.append({"role": "user", "content": "My name is Tanya. Please remember it."})
r1 = client.chat.completions.create(model=MODEL, messages=messages)
answer1 = r1.choices[0].message.content
print("Bot:", answer1)
messages.append({"role": "assistant", "content": answer1})   # write the reply in the notebook!

# ----- Turn 2 ----- (we resend the WHOLE notebook, so the name is still in there)
messages.append({"role": "user", "content": "What's my name?"})
r2 = client.chat.completions.create(model=MODEL, messages=messages)
answer2 = r2.choices[0].message.content
print("Bot:", answer2)   # "Your name is Tanya." ✅
messages.append({"role": "assistant", "content": answer2})

"""### LOCAL CHATBOT

##### Install OLLAMA
"""

!apt-get update -qq
!apt-get install -y zstd

!curl -fsSL https://ollama.com/install.sh | sh

# start the ollama server
import subprocess
import time

ollama = subprocess.Popen(
    ["ollama", "serve"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(5)
print("Ollama server started!")

# Download model
!ollama pull llama3.2:3b

"""##### Run Chatbot locally"""

"""
The SAME chatbot, but the model runs LOCALLY via Ollama.
No API key. No internet needed. 100% private and free.
Prereqs: Ollama installed + `ollama pull llama3.2` done.
"""
from openai import OpenAI

# 1) Point the client at your LOCAL Ollama 'house' instead of the cloud.
#    api_key is required by the library but Ollama ignores it - any text works.
client = OpenAI(
    base_url="http://127.0.0.1:11434/v1",
    api_key="ollama",
)

MODEL = "llama3.2:3b"   # must match a model you pulled

# 2) Same notebook (memory) as Project 1
messages = [
    {"role": "system", "content": "You are a friendly, concise assistant."}
]

print("🦙 Local Ollama Chatbot ready (running on YOUR machine)! Type 'quit' to leave.\n")

# 3) Same forever-loop as Project 1
while True:
    user_input = input("You: ").strip()
    if user_input.lower() in ("quit", "exit", "bye"):
        print("Bot: Goodbye! 👋")
        break
    if not user_input:
        continue

    messages.append({"role": "user", "content": user_input})

    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=0.7,
    )
    reply = response.choices[0].message.content

    print(f"Bot: {reply}\n")
    messages.append({"role": "assistant", "content": reply})

