# -*- coding: utf-8 -*-
"""04_OPEN_API_FEATURES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEbOgmy-VRqD7qfgv-QLKjHvzLHosdhs
"""

import os

# Set an environment variable
os.environ['GROQ_API_KEY'] = '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'
print("Environment variables set successfully.")

pip install groq

"""### KNOBS

def ask(label, prompt, **kwargs):

We make a small reusable helper function so we don't copy-paste the whole API call three times.

label → a title to print (so we know which test we're looking at).
prompt → the question to send.
**kwargs → 🧒 think of this as "a bag for any extra settings." Whatever knobs we pass when we call ask(...) (like max_tokens=25) get scooped into this bag and handed straight to the API. It's just a tidy way to pass through different settings each time.

resp = client.chat.completions.create(model=..., messages=..., **kwargs)
The same call you know from Module 3 — except **kwargs unpacks the bag of knobs into the request. So ask("...", "...", max_tokens=25) becomes a create(...) call with max_tokens=25 added.

resp.usage.completion_tokens
🔗 From Module 2/3 — how many tokens the answer used. Handy to watch what each knob costs.
"""

"""
The knobs (parameters) beyond temperature.
Runs FREE on Groq - identical to OpenAI's API.
"""
import os
from groq import Groq

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# A small reusable helper so we don't repeat the whole call each time
def ask(label, prompt, **kwargs):
    print(f"\n===== {label} =====")
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        **kwargs,            # <-- the knobs get passed in here
    )
    print(resp.choices[0].message.content)
    print(f"(completion tokens: {resp.usage.completion_tokens})")

# 1) max_tokens - hard ceiling on answer length (it CHOPS, mid-sentence if needed)
ask("max_tokens = 25 (gets cut off)",
    "Write a detailed paragraph about why the ocean matters.",
    max_tokens=25)

# 2) stop - the model halts the instant it would write '5'
ask("stop = ['5'] (counting stops around 5)",
    "Count from 1 to 10, one number per line.",
    stop=["5"])

# 3) seed - fixes the dice. Run this FILE twice; this answer should match both times.
ask("seed = 42, temperature = 0.8 (RUN TWICE, compare)",
    "Invent a quirky name for a coffee shop.",
    temperature=0.8, seed=42)

"""### STREAMING"""

"""
Streaming - get the answer word-by-word as it's written.
Runs FREE on Groq.
"""
import os
from groq import Groq

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"
PROMPT = "Write a short, upbeat paragraph about learning to code."

# ---------- THE NORMAL WAY: wait for the whole answer, then print ----------
print("=== NON-STREAMING (you wait... then it all appears at once) ===")
resp = client.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user", "content": PROMPT}],
)
print(resp.choices[0].message.content)

# ---------- STREAMING: print each piece the instant it arrives ----------
print("\n=== STREAMING (words flow in live) ===")
stream = client.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user", "content": PROMPT}],
    stream=True,                       # <-- the ONLY new setting
)

for chunk in stream:
    # print(f"{chunk}\n")
    piece = chunk.choices[0].delta.content or ""
    print(piece, end="", flush=True)
print()   # final newline

"""### Function Calling"""

"""
Function calling - the AI asks US to run real code.
Runs FREE on Groq.
"""
import os
import json
from groq import Groq

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# 1) OUR REAL TOOL: an ordinary Python function (our fake "database")
FAKE_DB = {"alice": 1240.50, "bob": 89.00, "carol": 5300.75}

def get_account_balance(user_id):
    balance = FAKE_DB.get(user_id.lower())
    if balance is None:
        return f"No account found for '{user_id}'."
    return f"{user_id}'s balance is ${balance:.2f}"

# 2) DESCRIBE the tool to the model (so it knows the bell exists + how to ring it)
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_account_balance",
            "description": "Get the current account balance for a given user id.",
            "parameters": {
                "type": "object",
                "properties": {
                    "user_id": {
                        "type": "string",
                        "description": "The user's id, e.g. 'alice'",
                    }
                },
                "required": ["user_id"],
            },
        },
    }
]

# 3) The user's question + the tool menu (the notebook starts here)
messages = [{"role": "user", "content": "What is Alice's account balance?"}]

# ----- TRIP 1: the wizard will REQUEST a tool, not answer -----
response = client.chat.completions.create(
    model=MODEL,
    messages=messages,
    tools=tools,                      # <-- hand over the menu of bells
)
reply = response.choices[0].message
print(f"reply:------------{reply}\n\n\n")
messages.append(reply)                # add the wizard's tool-request to the notebook

# 4) Did the wizard ring a bell?
if reply.tool_calls:
    for call in reply.tool_calls:
        fn_name = call.function.name
        args = json.loads(call.function.arguments)   # args arrive as JSON text
        print(f"🔔 Model wants to call: {fn_name}({args})")

        # 5) WE run the real Python function
        result = get_account_balance(**args)
        print(f"🛠️  Tool result: {result}")

        # 6) Hand the result back to the wizard (role 'tool')
        messages.append({
            "role": "tool",
            "tool_call_id": call.id,
            "content": result,
        })

    # ----- TRIP 2: now the wizard answers using the tool result -----
    final = client.chat.completions.create(model=MODEL, messages=messages)
    print("\n🤖 Final answer:", final.choices[0].message.content)
else:
    print("🤖 Answer (no tool needed):", reply.content)

"""### Structured Output"""

"""
Structured outputs - make the model return clean JSON.
Runs FREE on Groq.
"""
import os
import json
from groq import Groq
from pydantic import BaseModel

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

TEXT = "Tanvi Yadav is 25 years old and works as a data analyst in Delhi."

# ===== 1) BRUTE FORCE: ask nicely, hope for the best (often messy) =====
print("===== 1) BRUTE FORCE =====")
resp = client.chat.completions.create(
    model=MODEL,
    messages=[{"role": "user",
               "content": f"Give me JSON with name, age, job, city for: {TEXT}"}],
)
print(resp.choices[0].message.content)
print("(^ may have ```json fences or a 'Sure, here...' preamble - fragile)\n")

# ===== 2) JSON MODE: forces the WHOLE reply to be valid JSON =====
print("===== 2) JSON MODE =====")
resp = client.chat.completions.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "You output ONLY valid JSON, no extra text."},
        {"role": "user",
         "content": f"Extract keys name, age, job, city as JSON from: {TEXT}"},
    ],
    response_format={"type": "json_object"},     # <-- the magic switch
)
raw = resp.choices[0].message.content
print(raw)
data = json.loads(raw)                  # parses cleanly - nothing to strip
print("Parsed -> name:", data["name"], "| city:", data["city"], "\n")

# ===== 3) PYDANTIC: define + enforce the exact shape =====
print("===== 3) PYDANTIC =====")
class Person(BaseModel):
    name: str
    age: int        # forces a number, even if the model sent "25" as text
    job: str
    city: str

person = Person(**data)                 # validates + converts; errors loudly if wrong
print("Validated ->", person)
print("Safe to use ->", person.name, "is", person.age, "years old.")

