# -*- coding: utf-8 -*-
"""Project_Structured_data_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b21a0ENexY9X-WyOVjj_JzQPIyiSeRck
"""

# Messy text                                    Clean, validated data
#    "Hi, Ravi here,                               {
#     order #88231                                   "customer_name": "Ravi",
#     hasn't arrived,        ┌──────────────┐        "order_number": "88231",
#     3 weeks!! 😤"   ─────▶ │  extract()    │ ─────▶ "category": "shipping",
#                           │  Groq + JSON  │        "urgency": "high",
#                           │  mode + Pydantic│      "summary": "Order late by 3 weeks"
#                           └──────────────┘        }
#                                 │
#                           validates against
#                           our exact schema

import os

# Set an environment variable
os.environ['GROQ_API_KEY'] = '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'
print("Environment variables set successfully.")

pip install groq

import os
from groq import Groq
import json

client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# hit LLM model request to extract validated data

TEXT = "Hi, Ravi here, order #88231 hasn't arrived, 3 weeks!! 😤"

# Pydantic Method for data validation
from pydantic import BaseModel

class Customer_data(BaseModel):
  customer_name: str
  order_number: int
  category: str
  urgency: str
  summary: str

response = client.chat.completions.create(
    model = MODEL,
    messages = [
        { "role": "system", "content": "You are an AI assistant that will help me extract validated data, give me response in valid json, no extra text" },
        { "role": "user", "content": f"From my attached text: {TEXT}, extract validated data: customer_name, order_number, catgeory, urgency, summary" }
    ],
    temperature = 0.7,
    response_format={"type": "json_object"},
)

# print(response)
raw = response.choices[0].message.content
# print(raw)
data = json.loads(raw) # clean parsing
print(f"Parsed data: {data}")

# now i have recieved response, but I need to validate it using Pydantic
customer_data = Customer_data(**data)
print(customer_data)

"""
Project 3: Structured Data Extractor.
Turns messy customer-support messages into clean, validated JSON.
Runs FREE on Groq.
"""
import os
import json
from enum import Enum
from typing import Optional
from groq import Groq
from dotenv import load_dotenv
from pydantic import BaseModel, ValidationError

load_dotenv()
client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# ---------- 1) Define the EXACT shape we want out ----------
class Category(str, Enum):           # a "dropdown" - only these values allowed
    shipping = "shipping"
    refund = "refund"
    technical = "technical"
    account = "account"
    other = "other"

class Urgency(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"

class Ticket(BaseModel):
    customer_name: Optional[str] = None   # might not be in the message
    order_number: Optional[str] = None    # might not be in the message
    category: Category                    # must be one of the dropdown values
    urgency: Urgency
    summary: str

# ---------- 2) Ask the model to extract, forcing JSON ----------
def extract(message: str) -> Ticket:
    system = (
        "You extract structured data from customer support messages and reply "
        "ONLY with valid JSON. Use these exact keys: "
        "customer_name (string or null), order_number (string or null), "
        "category (one of: shipping, refund, technical, account, other), "
        "urgency (one of: low, medium, high), summary (one short sentence)."
    )
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": message},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )
    data = json.loads(resp.choices[0].message.content)
    return Ticket(**data)            # validate against our schema

# ---------- 3) Run it on some messy real-world messages ----------
inbox = [
    "Hi, this is Ravi. My order #88231 still hasn't shown up and it's been 3 weeks!! Really frustrated.",
    "I'd like a refund on my subscription please. It auto-renewed and I didn't want it.",
    "getting error E-401 every time i try to log in, can someone help asap",
    "Does your app work on Linux? Just curious before I buy.",
]

for msg in inbox:
    print("\n" + "=" * 60)
    print("MESSAGE:", msg)
    try:
        ticket = extract(msg)
        print("EXTRACTED:\n", ticket.model_dump_json(indent=2))
    except ValidationError as e:
        print("⚠️ Validation failed:", e)
    except Exception as e:
        print("⚠️ Error:", e)