# -*- coding: utf-8 -*-
"""Project_Groq CLI Chatbot with Memory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXK9Smrs4mUD-TTls3n2L94t8Trm49ql
"""

import os

# Set an environment variable
os.environ['GROQ_API_KEY'] = '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'
print("Environment variables set successfully.")

# Access an environment variable
api_key = os.getenv('GROQ_API_KEY')
print(f"Value of my api key: {api_key}")

pip install groq

import os
from groq import Groq

client = Groq(api_key=api_key)

MODEL = "llama-3.3-70b-versatile"

ROLE = ["system", "user", "assistant"]

MESSAGES = [{"role": ROLE[0], "content": "You are an AI assistant chatbot"}]

while(True):
  user_req = input("How can I help you? Enter false for exit.")

  if(user_req.strip().lower()=="false"):
    break;
  next_question = {"role": ROLE[1], "content":user_req}
  MESSAGES.append(next_question)

  response = client.chat.completions.create(
    model=MODEL,
    messages=MESSAGES,
    temperature=0.7
  )
  print(f"\n{response.choices[0].message.content}")
  MESSAGES.append({"role": ROLE[2], "content": response.choices[0].message.content})
print(MESSAGES)

"""
Project 1: Groq CLI Chatbot with Memory.
A command-line assistant that remembers the whole conversation.
Run:  python chatbot.py    (type 'quit' to leave)
"""
import os
from groq import Groq
from dotenv import load_dotenv

# 1) Setup - load key, create client, pick the model
load_dotenv()
client = Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL = "llama-3.3-70b-versatile"

# 2) The notebook (memory) starts with the bot's personality
messages = [
    {
        "role": "system",
        "content": "You are a friendly, concise assistant. "
                   "Answer clearly and avoid rambling.",
    }
]

print("🤖 Chatbot ready! Type 'quit', 'exit', or 'bye' to leave.\n")

# 3) The forever-loop: ask -> reply -> repeat
while True:
    user_input = input("You: ").strip()

    # 4) Let the user escape the loop
    if user_input.lower() in ("quit", "exit", "bye"):
        print("Bot: Goodbye! 👋")
        break

    # 5) Ignore empty input (just pressing Enter)
    if not user_input:
        continue

    # 6) Write the user's line into the notebook
    messages.append({"role": "user", "content": user_input})

    # 7) Hand the WHOLE notebook to the wizard
    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        temperature=0.7,
    )
    reply = response.choices[0].message.content

    # 8) Show the reply, and write it into the notebook too
    print(f"Bot: {reply}\n")
    messages.append({"role": "assistant", "content": reply})